global:
  scrape_interval: 3s
  scrape_timeout: 1s


scrape_configs:
  - job_name: minio-job
    metrics_path: /minio/v2/metrics/node
    scheme: http
    static_configs:
      - targets: ['minio:9000']